### ISSUE TITLE
Error after enable in mkdocs

### ISSUE THREAD

**Issue by KorDum** [landmaj/mkdocs-d2-plugin#16]
Hello!
Installed the plugin, but I get an error when running mkdocs.

```
INFO    -  mkdocs-d2-plugin: Using cache at .cache/plugin/d2/db (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/mkdocs/livereload/__init__.py", line 211, in _build_loop
    self.builder()
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, serve_url=None if is_clean else serve_url, dirty=is_dirty)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 265, in build
    config = config.plugins.on_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 587, in on_config
    return self.run_event('config', config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 566, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/d2/plugin.py", line 44, in on_config
    d2_version = version.parse(raw_version)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/packaging/version.py", line 54, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: ''
```

If I silence the error through an obsolete package `packaging==21.3`, it works fine

```
> pip list

annotated-types        0.7.0
beautifulsoup4         4.12.3
certifi                2024.2.2
charset-normalizer     3.3.2
click                  8.1.7
d2                     0.7
EditorConfig           0.12.4
ghp-import             2.1.0
idna                   3.7
Jinja2                 3.1.4
jsbeautifier           1.15.1
Markdown               3.6
MarkupSafe             2.1.5
mergedeep              1.3.4
mkdocs                 1.6.0
mkdocs-d2-plugin       1.3.3
mkdocs-get-deps        0.2.0
mkdocs-mermaid2-plugin 1.1.1
packaging              21.3
pathspec               0.12.1
pip                    24.0
platformdirs           4.2.2
pydantic               2.7.1
pydantic_core          2.18.2
pymdown-extensions     10.8.1
pyparsing              3.1.2
python-dateutil        2.9.0.post0
PyYAML                 6.0.1
pyyaml_env_tag         0.1
requests               2.32.2
setuptools             65.5.1
six                    1.16.0
soupsieve              2.5
tabulate               0.9.0
typing_extensions      4.11.0
urllib3                2.2.1
watchdog               4.0.0
wheel                  0.43.0
```

**Comment by landmaj** [comment]
Should be fixed in version `1.3.4`. Out of curiosity - what version of d2 (`d2 --version`) do you have?
