### ISSUE TITLE
d2-plugin crashes with privacy plugin enabled

### ISSUE THREAD

**Issue by tylernguyen** [landmaj/mkdocs-d2-plugin#21]
Hi, 

Per title, the d2-plugin seems to cause the privacy to crash. 

```
INFO    -  mkdocs-d2-plugin: Using cache at .cache/plugin/d2/db (dbm.gnu)
INFO    -  Cleaning site directory
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/__main__.py", line 272, in serve_command
    serve.serve(**kwargs)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 85, in serve
    builder(config)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, serve_url=None if is_clean else serve_url, dirty=is_dirty)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 292, in build
    files = config.plugins.on_files(files, config=config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 593, in on_files
    return self.run_event('files', files, config=config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 566, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/material/plugins/privacy/plugin.py", line 101, in on_files
    for url in self._parse_media(initiator):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/material/plugins/privacy/plugin.py", line 328, in _parse_media
    with open(initiator.abs_src_path, encoding = "utf-8-sig") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Not sure what is going on here. I also attached minimal build for reference.

**[bug.zip](https://github.com/user-attachments/files/17613287/bug.zip)**

**Comment by landmaj** [comment]
Please specify which package versions (mkdocs, mkdocs-material and mkdocs-d2-plugin) you have installed.

**Comment by tylernguyen** [comment]
I'm on the latest Insiders version `mkdocs-material-9.5.43-insiders-4.53.14`, mkdocs-d2-plugin version `1.3.0`, and mkdocs version `1.6`

**Comment by landmaj** [comment]
This is a bug in the privacy plugin. According to [MkDocs documentation](https://www.mkdocs.org/dev-guide/api/#mkdocs.structure.files.File):

> Since MkDocs 1.6 a file may alternatively be stored in memory - content_string/content_bytes.
> 
> Then src_dir and abs_src_path will remain None. content_bytes/content_string need to be written to, or populated through the content argument in the constructor.

[The privacy plugin does not handle that case and it assumes `abs_src_path` is safe to pass to `open` without checking.](https://github.com/squidfunk/mkdocs-material/blob/5c9ee60ab8209bfb167d3ce9a88025205062c0d4/src/plugins/privacy/plugin.py#L273)

This will most likely break other plugins relying on content_bytes/content_string in MkDocs 1.6 as well, so please create an issue in Material for MkDocs repository.

**Comment by landmaj** [comment]
Material for MkDocs version 9.5.49 fixes the issue: https://squidfunk.github.io/mkdocs-material/changelog/#9.5.49

**Comment by tylernguyen** [comment]
Hi there, 

I completely missed your first reply, apologies. Thank you escalating the issue and getting it fixed.
